In [1]:
import numpy as np

In [9]:
array = np.array([[1,2,3],[2,3,4]])
array
#print(array)     #print出来才是不带逗号的数组

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
print("维度:",array.ndim)
print("行数和列数:",array.shape)
print("元素个数:",array.size)

维度: 2
行数和列数: (2, 3)
元素个数: 6


Numpy的创建

In [20]:
a = np.array([11,22,33])
print(a)

[11 22 33]


In [21]:
a = np.array([11,22,33],dtype = np.int)   #默认64位
print(a.dtype)

int64


In [22]:
a = np.array([11,22,33],dtype = np.int32)
print(a.dtype)

int32


In [23]:
a  = np.array([11,22,33],dtype = np.float)
print(a)
print(a.dtype)

[11. 22. 33.]
float64


In [24]:
a = np.array([11,22,33],dtype = np.float32)
print(a)
print(a.dtype)

[11. 22. 33.]
float32


In [28]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
a = np.zeros((3,4),dtype=np.int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [32]:
a = np.empty((3,4), dtype = np.float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
a = np.empty((3,4), dtype = np.int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [34]:
a = np.arange(0,10,1)    #1为步长
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
a =np.arange(0,10,1).reshape((2,5))   #reshape里面要带括号
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [32]:
a = np.linspace(1,20,5)  #8表示分割成8个数据（等差数列）
print(a)

[ 1.    5.75 10.5  15.25 20.  ]


In [40]:
a = np.linspace(1,20,8).reshape((4,2))
print(a)

[[ 1.          3.71428571]
 [ 6.42857143  9.14285714]
 [11.85714286 14.57142857]
 [17.28571429 20.        ]]


In [34]:
import numpy as np
a=np.array([11,22,33,44,55,66])   
b=np.arange(6)  

In [35]:
print(a)
print(b)

[11 22 33 44 55 66]
[0 1 2 3 4 5]


In [36]:
c = a + b
print(c)

[11 23 35 47 59 71]


In [37]:
d = a - b
print(d)

[11 21 31 41 51 61]


In [38]:
e = a * b
print(e)

[  0  22  66 132 220 330]


In [39]:
f = a**2
print(f)

[ 121  484 1089 1936 3025 4356]


In [40]:
g = 2*np.sin(a)
print(g)
h = 2*np.cos(a)
print(h)

[-1.99998041 -0.01770262  1.99982372  0.03540385 -1.99951035 -0.05310231]
[ 0.0088514  -1.99992165 -0.02655349  1.99968662  0.04425351 -1.99929491]


In [41]:
print(a < 50)    #返回True / False
print(a == 44)

[ True  True  True  True False False]
[False False False  True False False]


In [42]:
a = np.array([[11,22,33],[44,55,66]])
b = np.arange(6).reshape((3,2))
print(a)
print(b)

[[11 22 33]
 [44 55 66]]
[[0 1]
 [2 3]
 [4 5]]


In [43]:
c_dot = np.dot(a,b)    #内积的两种写法
print(c_dot)
d_dot = a.dot(b)
print(d_dot)

[[176 242]
 [374 539]]
[[176 242]
 [374 539]]


In [45]:
import numpy as np
a=np.random.random((5,2))  #生成5行2列的浮点数，浮点数都是从0-1中随机。
print(a)
b=np.random.rand(5,2)    #生成一个[0,1)之间的随机浮点数或N维浮点数组
print(b)
c=np.random.randn(5,2)  #生成一个浮点数或N维浮点数组，取数范围：正态分布的随机样本数。
print(c)
d= np.random.standard_normal(5)   #生产一个浮点数或N维浮点数组，取数范围：标准正态分布随机样本
print(d)

[[0.27488251 0.38112198]
 [0.69079936 0.07863913]
 [0.61867795 0.28980118]
 [0.03101032 0.66391407]
 [0.84243695 0.63899964]]
[[0.60735054 0.66247893]
 [0.67776596 0.45331973]
 [0.90784201 0.50873135]
 [0.95642159 0.7387789 ]
 [0.56548098 0.77954772]]
[[ 1.49401173 -1.11708126]
 [ 0.34720045  0.6367115 ]
 [-0.31967077 -2.20778759]
 [-0.14534832  1.43130997]
 [-0.55667492 -0.09422262]]
[ 0.28125715  0.66325468  0.86256529 -0.5651094   0.72359101]


In [46]:
sum = np.sum(a)
print(sum)
min = np.min(a)
print(min)
max = np.max(a)
print(max)

4.510283102750235
0.031010324421880564
0.8424369537405353


In [ ]:
a = np.sum(a, axis = 1)

In [47]:
sum_hang = np.sum(a, axis = 1)   #axis:轴 1行0列
print(sum_hang)
min_lie = np.min(a, axis = 0)    #a中每列的最小值
print(min_lie)
max_hang = np.max(a, axis = 1)   #a中每行的最大值
print(max_hang)

[0.65600449 0.76943849 0.90847913 0.6949244  1.48143659]
[0.03101032 0.07863913]
[0.38112198 0.69079936 0.61867795 0.66391407 0.84243695]


# 最大值、最小值的索引

In [80]:
A = np.array([[11,22,33,44,55],[55,44,33,22,11],[0,22,44,66,88],[11,33,55,77,99]])
print(A)
print(np.argmin(A))
print(np.argmax(A))

[[11 22 33 44 55]
 [55 44 33 22 11]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]
10
19


In [86]:
A = np.array([[11,22,33,44,55],[55,44,33,22,11],[0,22,44,66,88],[11,33,55,77,99]])
print(A)
print(np.mean(A))
print(np.average(A))
print(A.mean())     #这种方法也可以，同理内积
print(np.median(A))

[[11 22 33 44 55]
 [55 44 33 22 11]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]
41.25
41.25
41.25
38.5


In [88]:
A = np.array([[11,22,33,44,55],[55,44,33,22,11],[0,22,44,66,88],[11,33,55,77,99]])
print(A)
print(np.cumsum(A))
print(np.diff(A))

[[11 22 33 44 55]
 [55 44 33 22 11]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]
[ 11  33  66 110 165 220 264 297 319 330 330 352 396 462 550 561 594 649
 726 825]
[[ 11  11  11  11]
 [-11 -11 -11 -11]
 [ 22  22  22  22]
 [ 22  22  22  22]]


In [89]:
A = np.array([[11,22,33,44,55],[55,44,33,22,11],[0,22,44,66,88],[11,33,55,77,99]])
print(A)
print(np.sort(A))

[[11 22 33 44 55]
 [55 44 33 22 11]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]
[[11 22 33 44 55]
 [11 22 33 44 55]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]


In [91]:
A = np.array([[11,22,33,44,55],[55,44,33,22,11],[0,22,44,66,88],[11,33,55,77,99]])
print(A)
print(np.transpose(A))
print(A.T)

[[11 22 33 44 55]
 [55 44 33 22 11]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]
[[11 55  0 11]
 [22 44 22 33]
 [33 33 44 55]
 [44 22 66 77]
 [55 11 88 99]]
[[11 55  0 11]
 [22 44 22 33]
 [33 33 44 55]
 [44 22 66 77]
 [55 11 88 99]]


In [93]:
A = np.array([[11,22,33,44,55],[55,44,33,22,11],[0,22,44,66,88],[11,33,55,77,99]])
print(A)
print(np.clip(A,44,77))   #小于44的都为44，大于77的都为77，其它照写

[[11 22 33 44 55]
 [55 44 33 22 11]
 [ 0 22 44 66 88]
 [11 33 55 77 99]]
[[44 44 44 44 55]
 [55 44 44 44 44]
 [44 44 44 66 77]
 [44 44 55 77 77]]


# 一维索引&二维索引

In [1]:
import numpy as np
A = np.arange(0,16)
print(A)   #一维索引
print(A[3])
A_reshape = np.arange(0,16).reshape((4,4))
print(A_reshape)
print(A_reshape[2])   #二维索引整行
print(A_reshape[2][2]) #二维索引具体

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
3
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 8  9 10 11]
10


In [2]:
import numpy as np
A = np.arange(0,16)
print(A)
A_reshape = np.arange(0,16).reshape((4,4))
print(A_reshape)
print(A_reshape[1][2])   #定位矩阵的具体值
print(A_reshape[1,2])   #此方法与上面方法一样
print(A_reshape[1,1:4])  #取某一行的某几个
print(A_reshape[2,:])  #取一整行

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6
6
[5 6 7]
[ 8  9 10 11]


In [3]:
import numpy as np
A = np.arange(0,16)
print(A)
A_reshape = np.arange(0,16).reshape((4,4))
print(A_reshape)
print('\n')
print(A_reshape.T)
print('\n')
for row in A_reshape:
    print(row)
print('\n')
for column in A_reshape.T:   #[记]求列要对矩阵转置一下
    print(column)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [8]:
import numpy as np
A = np.arange(0,16)
print(A)
A_reshape = np.arange(0,16).reshape((4,4))
print(A_reshape)
print(A_reshape.flatten())    #flatten有展平的意思 
print("",A_reshape.flat)
for item in A_reshape.flat:   #A_reshape.flat是一个迭代器
    print(item)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [9]:
import numpy as np
A = np.array([1,2,3,4,5,6])
B = np.array([6,5,4,3,2,1])

print(A)
print(B)
print(np.vstack((A,B)))    #沿着竖直方向将矩阵堆叠起来
C = np.vstack((A,B))
print(C)
print(A.shape , B.shape, C.shape)

[1 2 3 4 5 6]
[6 5 4 3 2 1]
[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
(6,) (6,) (2, 6)


In [10]:
import numpy as np
A = np.array([1,2,3,4,5,6]) 
B = np.array([6,5,4,3,2,1])
D = np.hstack((A,B))
print(D)
print(A.shape, B.shape, D.shape)

[1 2 3 4 5 6 6 5 4 3 2 1]
(6,) (6,) (12,)


In [62]:
import numpy as np
A = np.array([1,2,3,4,5,6]) 

print(A)
print(A.shape)
print(A[np.newaxis,:])  #在行方向加了一个维度
print(A[np.newaxis,:].shape)

print(A[:,np.newaxis])  #在列方向加了一个维度
print(A[:,np.newaxis].shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [18]:
import numpy as np
A = np.array([1,2,3,4,5,6])[:,np.newaxis]  #在列方向加了一个维度
B = np.array([6,5,4,3,2,1])[:,np.newaxis]
print(A)
print('\n')
print(B)
print('\n')
C = np.vstack((A,B))    #在垂直方向合并A、B
D = np.hstack((A,B))    ##在水平方向合并A、B
print(C)
print('\n')
print(D)
print(A.shape,B.shape,C.shape,D.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


[[6]
 [5]
 [4]
 [3]
 [2]
 [1]]


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [6]
 [5]
 [4]
 [3]
 [2]
 [1]]


[[1 6]
 [2 5]
 [3 4]
 [4 3]
 [5 2]
 [6 1]]
(6, 1) (6, 1) (12, 1) (6, 2)


In [19]:
import numpy as np
A = np.array([1,2,3,4,5,6])[:,np.newaxis]
B = np.array([6,5,4,3,2,1])[:,np.newaxis]

C = np.concatenate((A,A,B,B,A,A),axis = 1)    
print(C)
print('\n')
D = np.concatenate((A,A,B,B,A,A),axis = 0)
print(D)

[[1 1 6 6 1 1]
 [2 2 5 5 2 2]
 [3 3 4 4 3 3]
 [4 4 3 3 4 4]
 [5 5 2 2 5 5]
 [6 6 1 1 6 6]]


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [6]
 [5]
 [4]
 [3]
 [2]
 [1]
 [6]
 [5]
 [4]
 [3]
 [2]
 [1]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Numpy分割

In [2]:
import numpy as np
A = np.arange(1,25).reshape((4,6))

print(A)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [13]:
print(np.split(A, 3 ,axis = 1))  #纵向等分3列(第二个参数一定要能被总列数整除)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


In [15]:
print(np.split(A, 2, axis = 0))   #横向等分2行(第二个参数一定要能被总行数整除)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


In [18]:
print(np.array_split(A,4,axis = 1))  #6列分成了2、2、1、1

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5],
       [11],
       [17],
       [23]]), array([[ 6],
       [12],
       [18],
       [24]])]


In [20]:
print(np.array_split(A,3,axis = 0))  #4行分成了2、1、1

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


In [22]:
print(np.vsplit(A,2))  #等价于print(np.split(A, 2, axis = 0))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


In [23]:
print(np.hsplit(A,3))  #等价于print(np.split(A, 3 ,axis = 1))

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


# 浅拷贝与深拷贝

In [7]:
import numpy as np

a = np.arange(6)
print(a)
print('\n')
b = a
c = a
d = b
e = c
print(b)
print('\n')
print(c)
print('\n')
print(d)
print('\n')
print(e)
print('\n')

print(b is a)
print(c is b)
print(d is c)
print(e is d)

[0 1 2 3 4 5]


[0 1 2 3 4 5]


[0 1 2 3 4 5]


[0 1 2 3 4 5]


[0 1 2 3 4 5]


True
True
True
True


In [8]:
import numpy as np

a = np.arange(6)
a[0] = 100
print(a)
print('\n')
b = a
c = a
d = b
e = c
print(b)
print('\n')
print(c)
print('\n')
print(d)
print('\n')
print(e)
print('\n')

print(b is a)
print(c is b)
print(d is c)
print(e is d)

[100   1   2   3   4   5]


[100   1   2   3   4   5]


[100   1   2   3   4   5]


[100   1   2   3   4   5]


[100   1   2   3   4   5]


True
True
True
True


In [11]:
import numpy as np

a = np.arange(6)
print(a)
print('\n')
b = a.copy()
a[2] = 1000
print(a)
print('\n')      #b对a进行了深拷贝，当a的值改变时，b的值没有改变
print(b)

[0 1 2 3 4 5]


[   0    1 1000    3    4    5]


[0 1 2 3 4 5]
